import { Dimensions, Platform } from 'react-native';
import uuid from 'react-native-uuid';
import { MEDIA_TYPE } from './enums';
import { POST_TYPE } from './types';

export const CAROUSEL_SAFE_HORIZONTAL_INSETS = 20;
export const { width, height } = Dimensions.get('window');
export const POST_HEIGHT = Platform.OS === 'android' ? height / 1.7 : height / 2;
export const IMAGE_HEIGHT = POST_HEIGHT - 180;
export const HIT_SLOP_FOR_TOUCHABLES = {
  top: 8,
  left: 8,
  right: 8,
  bottom: 8,
};

export const SELECTION_LIMIT = 1;

export const EMAIL_REGEX = /^\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+$/;

const randomKey = () => uuid.v4();

export const LESS_POSTS: POST_TYPE[] = [
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://images.pexels.com/photos/14811468/pexels-photo-14811468.jpeg",
    },
    postLikes: [1, 1],
    description: "Wandering around beautiful land with wheat crops!",
    url: "http://res.cloudinary.com/dbr1a4zrz/video/upload/v1677233456/lewpnopfe7udgbmh0pdj.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://images.pexels.com/photos/14811468/pexels-photo-14811468.jpeg",
    },
    postLikes: [1, 1],
    description: "Wandering around beautiful land with wheat crops!",
    url: "http://res.cloudinary.com/dbr1a4zrz/video/upload/v1677254867/vggh9temlhamjgrdkz2p.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://images.pexels.com/photos/14811468/pexels-photo-14811468.jpeg",
    },
    postLikes: [1, 1],
    description: "Wandering around beautiful land with wheat crops!",
    url: "http://res.cloudinary.com/dbr1a4zrz/video/upload/v1677254910/dm4r0wpyi6ixuhojvqef.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://images.pexels.com/photos/14811468/pexels-photo-14811468.jpeg",
    },
    postLikes: [1, 1],
    description: "Wandering around beautiful land with wheat crops!",
    url: "http://res.cloudinary.com/dbr1a4zrz/video/upload/v1677254971/ztkugybuikvhcqax9rnf.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://images.pexels.com/photos/14811468/pexels-photo-14811468.jpeg",
    },
    postLikes: [1, 1],
    description: "Wandering around beautiful land with wheat crops!",
    url: "http://res.cloudinary.com/dbr1a4zrz/video/upload/v1677255018/mqxsxci7cpauleo0glxk.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://images4.alphacoders.com/936/936378.jpg", "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8NGslMjBtb3VudGFpbnxlbnwwfHwwfHw%3D"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-png-image-30mb.png", "https://sample-videos.com/img/Sample-png-image-30mb.png"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-png-image-30mb.png", "https://sample-videos.com/img/Sample-png-image-30mb.png"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-png-image-30mb.png", "https://sample-videos.com/img/Sample-png-image-30mb.png"],
    comments: [],
  },
]

export const POSTS: POST_TYPE[] = [
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://images4.alphacoders.com/936/936378.jpg", "https://images.unsplash.com/photo-1503614472-8c93d56e92ce?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8NGslMjBtb3VudGFpbnxlbnwwfHwwfHw%3D"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-png-image-30mb.png", "https://sample-videos.com/img/Sample-png-image-30mb.png"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-png-image-30mb.png", "https://sample-videos.com/img/Sample-png-image-30mb.png"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-png-image-30mb.png", "https://sample-videos.com/img/Sample-png-image-30mb.png"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-png-image-30mb.png", "https://sample-videos.com/img/Sample-png-image-30mb.png"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-png-image-30mb.png", "https://sample-videos.com/img/Sample-png-image-30mb.png"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.IMAGE,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    urls: ["https://sample-videos.com/img/Sample-jpg-image-10mb.jpg", "https://sample-videos.com/img/Sample-jpg-image-10mb.jpg"],
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "http://res.cloudinary.com/dbr1a4zrz/video/upload/v1677254867/vggh9temlhamjgrdkz2p.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "http://res.cloudinary.com/dbr1a4zrz/video/upload/v1677254867/vggh9temlhamjgrdkz2p.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "http://res.cloudinary.com/dbr1a4zrz/video/upload/v1677254867/vggh9temlhamjgrdkz2p.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1, 2],
  },
  {
    id: randomKey(),
    type: MEDIA_TYPE.VIDEO,
    user: {
      fullName: "Ravi Asthana",
      userName: "rantoinne",
      userAvatar: "https://img.freepik.com/free-vector/illustration-user-avatar-icon_53876-5907.jpg",
    },
    postLikes: [],
    description: "Caption",
    url: "https://res.cloudinary.com/dbr1a4zrz/video/upload/v1676916888/cro5madnd5wupbqmui0w.mp4",
    comments: [1],
  },
];
